### ISSUE TITLE
Data Structure ?

### ISSUE THREAD

**Issue by nmnhut0208** [dd1github/DeepSMOTE#2]
Hi, I am very interested in your repo right now. But I have some questions. In DeepSMOTE_MNIST.py file, line 178 "dtrnimg" is a txt file, why are you using os.listdir. Can you tell me the details of the data structure? Many thanks and look forward to reply from you soon.

**Comment by dd1github** [comment]
Thanks for your interest and for noticing this.  When the code was originally written, it was based on 5 fold cross-validation and hence there were 5 training and labeled .txt files per directory.  When I recently uploaded the data files (only a single training and labeled file is necessary to illustrate the workings of the model, instead of 5), I inadvertently mislabeled the path to the data files.  Some additional explanation has been added to the code around lines 175.  Hope this helps!
